# Generated by Django 3.2 on 2021-06-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_blog_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('img_link', models.CharField(max_length=1000)),
                ('thumb_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='add_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('img_link', models.CharField(max_length=1000)),
                ('thumb_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='atly_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
